language: android

android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - extra
    - addon
    - sys-img-armeabi-v7a-android-23
  licenses:
    - android-sdk-license-5be876d5

script:
  - ./gradlew build
