language: android

env:
  - TERM=dumb

notifications:
  email: false

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - extra
    - addon
    - sys-img-armeabi-v7a-android-23
  licenses:
    - android-sdk-license-5be876d5

script:
  - ./gradlew assemble

deploy:
  provider: releases
  api_key:
    secure: "liFwNkLNk+KvqFEZpkj124DCIkMPOBkeLArD2AmekvQLAEX/gTi5DmekRi/OG1iAZa0oy2FpXjs2mJbotevuhdSj3c+71vyiVpNVbjaq8/YtMyGX2Zz/lFaGneB7f4yxDCK5eAfYUk2mcrpyDp0mC6dDk+OJr/vE2PSQu2iH0JzNmzDZLEWZdxr1HLyRSCz++bqAEopHdAHmuzQOySZ2yvITF1ePUS18Ihcu+w4y5lk1cYc7KX4UnzPCFbdG1Z6Bm4J9VwjtVXlmKOBfQVyNTAVryXdXmyjsl4TpQMyzR3zVGQJ4tTM9WVqTanxEfZevqUB+r/e+BE+ktHkygKJISEYPnW4igoSENnr7aCH+MuhJ+1vuza8ajoLot1NYDGnzY26+GNFYfnYQg5v+Cig00DMspTNydpkvuY/wlbC5oxt+cuf17pPEClabBuhThk9pcWmytTro4TIjNNHb6Oa3H8f2ULJH4t9xdJsyUw+TvMRmwKpFhEQtxN0Sx3KgiZFhLmCeYqj7skqLrJ/8IXC7sZo7BgWoZJ63ABHr9hVZ4/8H/FyUqPfHWcdQNElgbZ71EaZPH695FDJLNcWrrMY3MUCSP4rpbP62Pam1mR46/1WOI99Rcjt8qCdfu0BK6nkEOoarGWX+1T4gR5zP8NNsXhjF1+bIaeh56mqa73yZNak="
  file_glob: true
  file:
    - app/build/outputs/apk/app-debug*.apk
    - app/build/outputs/apk/app-release*.apk
  skip_cleanup: true
  on:
    repo: Sloy/github-releases-android
    tags: true
